# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ui/main.ui'
#
# Created: Mon Apr 22 08:57:31 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.resize(1300, 700)
        self.centralwidget = QtGui.QWidget(main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../Code/ImgFundacion.JPG")))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit.setPalette(palette)
        self.textEdit.setMouseTracking(True)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtGui.QFrame.Sunken)
        self.textEdit.setAutoFormatting(QtGui.QTextEdit.AutoNone)
        self.textEdit.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.textEdit.setLineWrapColumnOrWidth(50)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.verticalLayout.addWidget(self.commandLinkButton_2)
        self.commandLinkButton_7 = QtGui.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_7.setObjectName(_fromUtf8("commandLinkButton_7"))
        self.verticalLayout.addWidget(self.commandLinkButton_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.groupBox)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.commandLinkButton_4 = QtGui.QCommandLinkButton(self.groupBox_2)
        self.commandLinkButton_4.setObjectName(_fromUtf8("commandLinkButton_4"))
        self.verticalLayout_2.addWidget(self.commandLinkButton_4)
        self.commandLinkButton_5 = QtGui.QCommandLinkButton(self.groupBox_2)
        self.commandLinkButton_5.setObjectName(_fromUtf8("commandLinkButton_5"))
        self.verticalLayout_2.addWidget(self.commandLinkButton_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        main.setStatusBar(self.statusbar)
        self.actionRegistrar_Donante = QtGui.QAction(main)
        self.actionRegistrar_Donante.setObjectName(_fromUtf8("actionRegistrar_Donante"))
        self.actionModificar_Donante = QtGui.QAction(main)
        self.actionModificar_Donante.setObjectName(_fromUtf8("actionModificar_Donante"))
        self.actionModificar_Donante_2 = QtGui.QAction(main)
        self.actionModificar_Donante_2.setObjectName(_fromUtf8("actionModificar_Donante_2"))
        self.actionEliminar_Donante = QtGui.QAction(main)
        self.actionEliminar_Donante.setObjectName(_fromUtf8("actionEliminar_Donante"))
        self.actionBuscar_Donante = QtGui.QAction(main)
        self.actionBuscar_Donante.setObjectName(_fromUtf8("actionBuscar_Donante"))
        self.actionBuscar_Donacion = QtGui.QAction(main)
        self.actionBuscar_Donacion.setCheckable(False)
        self.actionBuscar_Donacion.setPriority(QtGui.QAction.NormalPriority)
        self.actionBuscar_Donacion.setObjectName(_fromUtf8("actionBuscar_Donacion"))
        self.actionRegistrar_Donacion = QtGui.QAction(main)
        self.actionRegistrar_Donacion.setObjectName(_fromUtf8("actionRegistrar_Donacion"))
        self.actionModificar_Donacion = QtGui.QAction(main)
        self.actionModificar_Donacion.setObjectName(_fromUtf8("actionModificar_Donacion"))
        self.actionEliminar_Donacion = QtGui.QAction(main)
        self.actionEliminar_Donacion.setObjectName(_fromUtf8("actionEliminar_Donacion"))
        self.actionSalir = QtGui.QAction(main)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))

        self.retranslateUi(main)
        QtCore.QObject.connect(self.commandLinkButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), main.goRegistrarDonante)
        QtCore.QObject.connect(self.commandLinkButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), main.goGestionarDonantes)
        QtCore.QObject.connect(self.commandLinkButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), main.goGestionarDonaciones)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        main.setWindowTitle(_translate("main", "Sistema SMD", None))
        self.textEdit.setHtml(_translate("main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bienvenido a SMD, un sistema práctico y confiable que le ayudará a llevar el control de los donantes y donaciones involucradas con la organización. Específicamente puede registrar, modificar, eliminar donantes y donaciones. Tambien el sistema le permite realizar búsquedas detalladas de tipos de donaciones y donantes.</p></body></html>", None))
        self.groupBox.setTitle(_translate("main", "Donante", None))
        self.commandLinkButton_2.setText(_translate("main", "Registrar Donante", None))
        self.commandLinkButton_7.setText(_translate("main", "Gestionar Donantes", None))
        self.groupBox_2.setTitle(_translate("main", "Donaciones", None))
        self.commandLinkButton_4.setText(_translate("main", "Registrar Donacion", None))
        self.commandLinkButton_5.setText(_translate("main", "Gestionar Donaciones", None))
        self.actionRegistrar_Donante.setText(_translate("main", "Registrar Donante", None))
        self.actionModificar_Donante.setText(_translate("main", "Modificar Donante", None))
        self.actionModificar_Donante_2.setText(_translate("main", "Modificar Donante", None))
        self.actionEliminar_Donante.setText(_translate("main", "Eliminar Donante", None))
        self.actionBuscar_Donante.setText(_translate("main", "Buscar Donantes", None))
        self.actionBuscar_Donacion.setText(_translate("main", "Buscar Donaciones", None))
        self.actionRegistrar_Donacion.setText(_translate("main", "Registrar Donación", None))
        self.actionModificar_Donacion.setText(_translate("main", "Modificar Donacion", None))
        self.actionEliminar_Donacion.setText(_translate("main", "Eliminar Donación", None))
        self.actionSalir.setText(_translate("main", "Salir", None))

