# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ui/registrar_donante.ui'
#
# Created: Thu Apr 18 11:27:52 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_registrarDonante(object):
    def setupUi(self, registrarDonante):
        registrarDonante.setObjectName(_fromUtf8("registrarDonante"))
        registrarDonante.resize(1300, 720)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(registrarDonante.sizePolicy().hasHeightForWidth())
        registrarDonante.setSizePolicy(sizePolicy)
        self.form_2 = QtGui.QWidget(registrarDonante)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_2.sizePolicy().hasHeightForWidth())
        self.form_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.form_2.setFont(font)
        self.form_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.form_2.setObjectName(_fromUtf8("form_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.form_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.form = QtGui.QFormLayout()
        self.form.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.form.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.form.setRowWrapPolicy(QtGui.QFormLayout.DontWrapRows)
        self.form.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.form.setFormAlignment(QtCore.Qt.AlignCenter)
        self.form.setMargin(9)
        self.form.setHorizontalSpacing(9)
        self.form.setObjectName(_fromUtf8("form"))
        self.label_3 = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.form.setWidget(1, QtGui.QFormLayout.SpanningRole, self.label_3)
        self.label_RIF = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_RIF.sizePolicy().hasHeightForWidth())
        self.label_RIF.setSizePolicy(sizePolicy)
        self.label_RIF.setObjectName(_fromUtf8("label_RIF"))
        self.form.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_RIF)
        self.Rif_Ci = QtGui.QLineEdit(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rif_Ci.sizePolicy().hasHeightForWidth())
        self.Rif_Ci.setSizePolicy(sizePolicy)
        self.Rif_Ci.setObjectName(_fromUtf8("Rif_Ci"))
        self.form.setWidget(2, QtGui.QFormLayout.FieldRole, self.Rif_Ci)
        self.label_registrado = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_registrado.sizePolicy().hasHeightForWidth())
        self.label_registrado.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(250, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_registrado.setPalette(palette)
        self.label_registrado.setText(_fromUtf8(""))
        self.label_registrado.setObjectName(_fromUtf8("label_registrado"))
        self.form.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_registrado)
        self.label = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.form.setWidget(4, QtGui.QFormLayout.FieldRole, self.label)
        self.label_razon = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_razon.sizePolicy().hasHeightForWidth())
        self.label_razon.setSizePolicy(sizePolicy)
        self.label_razon.setObjectName(_fromUtf8("label_razon"))
        self.form.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_razon)
        self.razon = QtGui.QLineEdit(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.razon.sizePolicy().hasHeightForWidth())
        self.razon.setSizePolicy(sizePolicy)
        self.razon.setReadOnly(False)
        self.razon.setObjectName(_fromUtf8("razon"))
        self.form.setWidget(5, QtGui.QFormLayout.FieldRole, self.razon)
        self.label_tipo_don = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tipo_don.sizePolicy().hasHeightForWidth())
        self.label_tipo_don.setSizePolicy(sizePolicy)
        self.label_tipo_don.setObjectName(_fromUtf8("label_tipo_don"))
        self.form.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_tipo_don)
        self.natural = QtGui.QRadioButton(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.natural.sizePolicy().hasHeightForWidth())
        self.natural.setSizePolicy(sizePolicy)
        self.natural.setCheckable(True)
        self.natural.setObjectName(_fromUtf8("natural"))
        self.form.setWidget(6, QtGui.QFormLayout.FieldRole, self.natural)
        self.juridico = QtGui.QRadioButton(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juridico.sizePolicy().hasHeightForWidth())
        self.juridico.setSizePolicy(sizePolicy)
        self.juridico.setCheckable(True)
        self.juridico.setObjectName(_fromUtf8("juridico"))
        self.form.setWidget(7, QtGui.QFormLayout.FieldRole, self.juridico)
        self.label_telf = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_telf.sizePolicy().hasHeightForWidth())
        self.label_telf.setSizePolicy(sizePolicy)
        self.label_telf.setObjectName(_fromUtf8("label_telf"))
        self.form.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_telf)
        self.telefono = QtGui.QLineEdit(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.telefono.sizePolicy().hasHeightForWidth())
        self.telefono.setSizePolicy(sizePolicy)
        self.telefono.setReadOnly(False)
        self.telefono.setObjectName(_fromUtf8("telefono"))
        self.form.setWidget(8, QtGui.QFormLayout.FieldRole, self.telefono)
        self.label_2 = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.form.setWidget(9, QtGui.QFormLayout.FieldRole, self.label_2)
        self.label_direc = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_direc.sizePolicy().hasHeightForWidth())
        self.label_direc.setSizePolicy(sizePolicy)
        self.label_direc.setObjectName(_fromUtf8("label_direc"))
        self.form.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_direc)
        self.direccion = QtGui.QTextEdit(self.form_2)
        self.direccion.setReadOnly(False)
        self.direccion.setObjectName(_fromUtf8("direccion"))
        self.form.setWidget(10, QtGui.QFormLayout.FieldRole, self.direccion)
        self.label_obs = QtGui.QLabel(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_obs.sizePolicy().hasHeightForWidth())
        self.label_obs.setSizePolicy(sizePolicy)
        self.label_obs.setObjectName(_fromUtf8("label_obs"))
        self.form.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_obs)
        self.obs = QtGui.QTextEdit(self.form_2)
        self.obs.setReadOnly(True)
        self.obs.setObjectName(_fromUtf8("obs"))
        self.form.setWidget(11, QtGui.QFormLayout.FieldRole, self.obs)
        self.pushButton = QtGui.QPushButton(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.form.setWidget(12, QtGui.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.form_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.form.setWidget(12, QtGui.QFormLayout.FieldRole, self.pushButton_2)
        self.label_4 = QtGui.QLabel(self.form_2)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("../Code/ImgFundacion.JPG")))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.form.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_4)
        self.verticalLayout.addLayout(self.form)
        registrarDonante.setCentralWidget(self.form_2)
        self.menubar = QtGui.QMenuBar(registrarDonante)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        registrarDonante.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(registrarDonante)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        registrarDonante.setStatusBar(self.statusbar)

        self.retranslateUi(registrarDonante)
        QtCore.QObject.connect(self.telefono, QtCore.SIGNAL(_fromUtf8("editingFinished()")), registrarDonante.verified_telefono)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), registrarDonante.verifiedAndSave)
        QtCore.QObject.connect(self.natural, QtCore.SIGNAL(_fromUtf8("pressed()")), registrarDonante.select_natural)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), registrarDonante.cancel)
        QtCore.QObject.connect(self.juridico, QtCore.SIGNAL(_fromUtf8("pressed()")), registrarDonante.select_juridico)
        QtCore.QObject.connect(self.Rif_Ci, QtCore.SIGNAL(_fromUtf8("editingFinished()")), registrarDonante.verified_Rif_Ci)
        QtCore.QMetaObject.connectSlotsByName(registrarDonante)

    def retranslateUi(self, registrarDonante):
        registrarDonante.setWindowTitle(_translate("registrarDonante", "Registrar Donante", None))
        self.label_3.setText(_translate("registrarDonante", "Registrar Donante", None))
        self.label_RIF.setText(_translate("registrarDonante", "RIF/CI:", None))
        self.label.setText(_translate("registrarDonante", "-Natural: V-12345678 o E-12345678   -Jurídica:J-12345678-9", None))
        self.label_razon.setText(_translate("registrarDonante", "Razón Social:", None))
        self.label_tipo_don.setText(_translate("registrarDonante", "Tipo de Donante:", None))
        self.natural.setText(_translate("registrarDonante", "Natural", None))
        self.juridico.setText(_translate("registrarDonante", "Jurídico", None))
        self.label_telf.setText(_translate("registrarDonante", "Teléfono:", None))
        self.label_2.setText(_translate("registrarDonante", "Ejemplo: 0212-1234567", None))
        self.label_direc.setText(_translate("registrarDonante", "Dirección:", None))
        self.label_obs.setText(_translate("registrarDonante", "Observaciones del sistema:", None))
        self.pushButton.setText(_translate("registrarDonante", "Registrar", None))
        self.pushButton_2.setText(_translate("registrarDonante", "Cancelar", None))

